#!/usr/bin/env python
#coding:gbk
#Copyright (C) dirlt

import os
import glob
env=Environment(CPPPATH=['../../'],
                CXXFLAGS='-W -Wall -g -Werror -O2 -DDEBUG -fPIC',
                LIBPATH=['../',
                         '../../common'],
                LIBS=['astyle',
                      'common',
                      'pthread'])

excepts=[]
for x in glob.glob('*.cc'):
    if x in excepts:
        continue
    env.Program(os.path.splitext(x)[0]+'.exe',[x])
