#!/usr/bin/env python
#coding:utf-8
#Copyright (C) dirlt

HEAD = """
<meta name="baidu-site-verification" content="707024a76f8f40b549f07f478abab237"/>
""".replace('\n','')

HEAD_END = """
""".replace('\n','')

BODY = """
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">
<a class="bds_tsina"></a>
<span class="bds_more"></span>
<a class="shareCount"></a>
</div>
""".replace('\n','')

BODY_END = """
<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%%3F54a700ad7035f6e485eaf2300641e7e9' type='text/javascript'%%3E%%3C/script%%3E"));
</script>

<!-- Baidu Button BEGIN -->
<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=6762177" ></script>
<script type="text/javascript" id="bdshell_js"></script>
<script type="text/javascript"> document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + Math.ceil(new Date()/3600000)</script>
<!-- Baidu Button END -->

<!-- DISQUS BEGIN -->
<div id="disqus_thread"></div>
<script type="text/javascript">
/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
/* required: replace example with your forum shortname  */
var disqus_shortname = 'dirlt';
var disqus_identifier = '%(id)s';
var disqus_title = '%(id)s';
var disqus_url = 'http://dirlt.com/%(id)s';
/* * * DON'T EDIT BELOW THIS LINE * * */
(function() {
var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
<!-- DISQUS END -->
""".replace('\n','')

import glob
import string
for f in glob.glob('../www/*.html')+glob.glob('../www/note/*.html'):
    xs=map(lambda s:string.strip(s),open(f, 'r').readlines())
    id = f[len('../www/'):]
    ds=[]
    for x in xs:
        if x.find('<head>') != -1 and not x == '<head>' + HEAD:
            ds.append('<head>' + HEAD)
        elif x.find('<body>') != -1 and not x == '<body>' + BODY:
            ds.append('<body>' + BODY)            
        elif x.find('</head>') != -1 and not x == HEAD_END + '</head>':
            ds.append(HEAD_END + '</head>')
        elif x.find('</body>') != -1 and not x == BODY_END%(locals()) + '</body>':
            ds.append(BODY_END%(locals()) + '</body>')            
        else:
            ds.append(x)
    print 'add code to \'%s\''%(f)
    open(f,'w').writelines(map(lambda x:x + '\n', ds))
    
