#!/usr/bin/env python
#coding:utf-8
#Copyright (C) dirlt

BAIDU_STAT="""<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F54a700ad7035f6e485eaf2300641e7e9' type='text/javascript'%3E%3C/script%3E"));
</script>"""

BAIDU_SHARE="""<!-- Baidu Button BEGIN -->
<div id="bdshare" class="bdshare_t bds_tools get-codes-bdshare">
<a class="bds_tsina"></a>
<span class="bds_more"></span>
<a class="shareCount"></a>
</div>
<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=6762177" ></script>
<script type="text/javascript" id="bdshell_js"></script>
<script type="text/javascript">
document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + Math.ceil(new Date()/3600000)
</script>
<!-- Baidu Button END -->"""

CODE = BAIDU_STAT + BAIDU_SHARE
CODE = CODE.replace('\n','')

import string
import glob
for f in glob.glob('../www/*.html')+glob.glob('../www/note/*.html'):
    s=map(lambda s:string.strip(s),open(f,'r').readlines())
    d=[]
    for x in s:
        if x.startswith('<body>') and not x == '<body>' + CODE:
            d.append('<body>' + CODE + '\n')
        else:
            d.append(x + '\n')
    print 'add code to \'%s\''%(f)    
    open(f,'w').writelines(d)


