#!/usr/bin/env python
#coding:utf-8
#Copyright (C) dirlt

HEAD = """
<meta name="baidu-site-verification" content="707024a76f8f40b549f07f478abab237"/>
""".replace('\n','')

BODY = """
<div id="bdshare" class="bdshare_t bds_tools_32 get-codes-bdshare">
<a class="bds_tsina"></a>
<span class="bds_more"></span>
<a class="shareCount"></a>
</div>
""".replace('\n','')

END = """<!-- END --><html><body>
<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F54a700ad7035f6e485eaf2300641e7e9' type='text/javascript'%3E%3C/script%3E"));
</script>

<!-- Baidu Button BEGIN -->
<script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=6762177" ></script>
<script type="text/javascript" id="bdshell_js"></script>
<script type="text/javascript"> document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + Math.ceil(new Date()/3600000)</script>
<!-- Baidu Button END -->
""".replace('\n','')

import glob
import string
for f in glob.glob('../www/*.html')+glob.glob('../www/note/*.html'):
    xs=map(lambda s:string.strip(s),open(f, 'r').readlines())

    # preprocess end.
    if xs[-1].startswith('<!-- END -->'):
        if not xs[-1] == END:
            xs[-1] = END
    else:
        xs.append(END)

    ds=[]
    for x in xs:
        if x.startswith('<head>') and not x == '<head>' + HEAD:
            ds.append('<head>' + HEAD)
        elif x.startswith('<body>') and not x == '<body>' + BODY:
            ds.append('<body>' + BODY)
        else:
            ds.append(x)
    print 'add code to \'%s\''%(f)
    open(f,'w').writelines(map(lambda x:x + '\n', ds))
    
