#!/usr/bin/env python
#coding:utf-8
#Copyright (C) dirlt

BAIDU_STAT="""<html><body>
<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F54a700ad7035f6e485eaf2300641e7e9' type='text/javascript'%3E%3C/script%3E"));
</script></body></html>"""

import glob
for x in glob.glob('../www/*.html')+glob.glob('../www/note/*.html'):
    d=open(x,'r').read()
    if(not d.endswith(BAIDU_STAT)):
        print 'add stat code to \'%s\''%(x)
        open(x,'a').write(BAIDU_STAT)


