* computational-advertising
#+OPTIONS: H:5

** 在线广告综述
*** 广告的定义与目的
   - 参与方 
     - 需求方(Demand): 可以是广告主(advertiser),代表广告主利益的代理商(agency)或者其它技术形态的采买方
     - 供给方(Supply): 可以是媒体,也可以是其他技术形态的变现平台。
     - 受众(Audience)
   - 广告目的：广告主通过媒体达到低成本的用户接触。
   - 品牌广告(Brand Awareness): 希望借助媒体的力量来快速接触大量用户,以达到宣传品牌形象,提升中长期购买率与利润空间的目的。
   - 效果广告(Direct Response): 希望能利用广告手段马上带来大量的购买行为。

*** 在线广告类型
   - 条幅广告(Banner Ad): 这是显示广告中中最传统,也是最典型的形式。这种广告一般是嵌入在页面中相对固定位置的图片,与内容一样需要占据固定的版面。
   - 文字链广告(Textual Ad): 这种广告的素材形式是一段链接到广告主落地页的文字,在搜索广告中为主流形式,同时在媒体广告中也被广泛采用。
   - 富媒体广告(Rich Media Ad): 这类广告往往是利用视觉冲击力较强的表现形式,在不占用固定版面位置的情况下,向用户侵入式地投送广告素材。
     - 富媒体广告常见的形式有弹窗、对 联、全屏等。它比较适合在高质量的媒体做一些品牌性质比较强的广告投放,但是对用户的使用体验往往影响也较大。
     - 一些门户网站的首页有时会为某个品牌广告主提供专门定制的、交互形式很复杂的富媒体广告, *这样的广告一般不采用受众定向的投送方式,也主要强调创意的冲击力和交互形式的特色。*
   - 视频广告(Video Ad): 视频广告有两种最主要的形式:在视频内容播放之前的前插片广告,以及视频播放暂停时的广告。前插片广告一般采用短视频的形式,创意的冲击力和表现力要远远强于普通的显示广告,因此CPM价格往往也比较高;暂停广告则与普通的条幅广告区别不大。
   - 社交广告(Social Ad): 社交广告中最典型的形式,是插入在社交网络信息流中的广告,这种方式最早见于Twitter,产品称为“Promoted Tweets”。社交广告希望达到的效果,是通过用户的扩散式传播获 得更大的影响力,以及更可信的口碑.
   - 移动设备广告(Mobile Ad): 
   - 邮件营销广告(Email Direct Marketing, EDM):
 
*** 在线广告简史
   1. 把网站的HTML页面当成是杂志的版面,在里面插入广告位,按照杂志的广告那样去售卖。
      - 这种在互联网上展示条幅(banner)广告创意的产品形式,我们称为显示广告(Display Advertising)。
      - 合约式广告(Agreement-based Advertising): 即采用合同约定的方式确定某一广告位在某一时间段为某特定广告主所独占,并且根据双方的要求,确定广告创意的允许范围以及同一页面上的某种广告主排他策略。
   2. 我们是可以对不同的受众呈现不同的广告创意的! 定向广告(Targeted Advertising) *NOTE(dirlt):依然是合约式广告和显示广告*
      - 受众定向(Audience Targeting),即通过技术手段标定某个用户的性别、年龄或其他标签。
      - 广告投放机(Ad Server),它将广告投送由直接嵌入页面变为实时响应前端请求,并根据用户标签自动决策和返回合适的广告创意。
      - 由于从传统的品牌广告市场直接延伸而来,此时的定向广告仍然以合约的方式进行:  *媒体向广告主保证某个投放量,并在此基础上确定合同的总金额以及量未完成情况下的赔偿方案。这种“担保式投送(Guaranteed Delivery)”* 的交易方式,逐渐成为互联网合约式广告的主要商业模式。
      - 一般来说,这样的广告合约仍然主要面向品牌广告主,并且按照按千次展示付费(Cost Per Mille, CPM)的计费方式。
      - 定向投放的最初动机,是供给方为了拆分流量以获得更高的营收。如果一开始就提供非常精细的定向,反而会造成售卖率的下降,因此,最初的定向标签往往都设置在在较粗的粒度上,最典型的是一些人口属性标签。 *NOTE（dirlt）：我的理解是，初期广告主也没有办法了解细分的定向* 
   3. 在受众定向的环境下合约广告系统问题和瓶颈
      - 在满足各合约目标受众量要求的同时,尽可能为所有广告商分配到质更好的流量。
	- 如何有效地将流量分配到各个合约互相交叉的人群覆盖上;
	- 在线的环境下实时且经济地完成每一次展示决策。
	- 在线分配问题（Online Allocation）
      - 受众定向产生以后,市场向着精细化运作的方向快速发展,主要有两方面的发展趋势:
	- 一是定向标签变得越来越精准;
	- 二是广告主的数量不断膨胀。
      - 在这些趋势下,仍然按照合约的方式售卖广告会碰到越来越多的麻烦:
	- 首先,很难对这些细粒度标 签组合的流量做准确预估;
	- 其次,当一次展示同时满足多个合约的时候,仅仅按照量约束下的在线分配策略进行决策,有可能浪费掉了很多本来可以卖得更贵的流量
   4. 大胆一点,抛弃量的保证,而采用最唯利是图的策略来进行广告决策? 竞价广告(Auction-based Advertising)。
      - 在这种模式下,供给方只向广告主保证质即单位流量的成本,但不再以合约的方式给出量的保证, 换言之,对每一次展示,都基本按照收益最高的原则来决策。
      - 竞价广告产生的最初场景,是在互联网广告最主要的金矿搜索广告(Search Ad)中。从广告的视角来看,我们也可以把付费搜索看做一种定向广告,即根据用户的即时兴趣定向投送的广告,而即时兴趣的标签就是关键词。很显然,这 种定向广告从一开始就直接达到了非常精准的程度,也就很自然地采用了竞价的方式售卖。
      - 当搜索广告产生了巨大的收益以后,搜索引擎开始考虑将这样的变现方式推广到其他互联网媒体上:将用户的即时兴趣标签有搜索词换成正在浏览页面中提取的关键词,可以将这套竞价广告系统从搜索结果页照搬到媒体页面上,这就产生了上下文广告(Contextual Advertising)。
      - 从宏观市场上看,竞价广告与合约广告有很大的不同。没有了合约的保证,大量的广告主处在一个多方博弈的环境中。与直觉不同的是,在如何收取广告主费用这一点上,我们并非按照微观上最优的方案实施,就可以达到整个市场最大的收益。关于定价机制的深入研究,产生了广义第二高价(Generalized Second Pricing)这一竞价重要的理论。 *NOTE（dirlt）：竞价广告出现定价机制*
   5. 基于竞价机制和精准人群定向这两个核心功能,在线广告分化出了广告网络(Ad Network)这种新的市场形态。
      - 它批量地运营媒体的广告位资源,按照人群或上下文标签售卖给需求方,在需求发生冲突时用竞价的方式决定流量分配。
      - 广告网络的结算,以按点击付费(Cost per Click, CPC)的方式为主。虽然我们不太能指 这种方式的千次展示收益(Revenue per Mille, RPM)可以达到合约式品牌广告的水平,但它使得大量中小互联网媒体有了切实可行的变现手段:这些媒体有一定的流量,但还不值得建立自己的销售团队面向品牌广告商售卖,直接把自己的广告库存(Inventory)托管给广告网络,借助广告网络的销售和代理团队为自己的流量变现。
   6. 在广告网络中,核心的竞价逻辑是封闭的。这种封闭的竞价机制,仍然不能完全满足需求方越来越明确的利益要求。这样的目标催生了实时竞价(Real Time Bidding)技术。
      - 试想下面的两个例子:一、某电子商务网站需要通过一次广告投放来向它的忠实用户推广某产品;二、某银行希望通过自己的信用卡用户在网络上找到类似 的潜在用户群,并通过广告争取这批潜在用户。 *NOTE（dirlt）：主要是这个受众定向太具体了，广告网络不可能计算出来什么是所谓的忠实用户因为和电商网站的访问数据过于相关*
      - 很显然,任何广告网络都不可能直接为这两个需 求提供人群标签。与其想办法满足这些不断产生的定制化需求,不如干脆设计一种开放的竞价逻 辑,让需求方按自己的人群定义来挑选流量!
      - 所谓实时竞价,就是把拍卖的过程由广告主预先出价,变成每次展示时实时出价。只要把广告展示的上下文页面url,以及访客的cookie等信息传给需求方,它就有充分的信息来完成定制化的人群选择和出价。
      - 需要注意的是,越是定制化的人群选择,往往就越精细,也就意味着单一媒体能达到的reach会相当有限。于是,市场上产生了大量聚合各媒体的剩余流量,采用实时竞价方式为他们变现的产品形态：广告交易平台(Ad Exchange)。 *NOTE（dirlt）：将各式各样的媒体信息聚合起来使用*

