#!/usr/bin/env python
#coding:gbk
#Copyright (C) dirlt

import os
env=Environment(CPPPATH=['../../'],
                CXXFLAGS='-W -Wall -g -Werror -O2 -DDEBUG -fPIC',
                LIBPATH=['../'],
                LIBS=['nasty'])
env.Program('test_parser.exe',
            ['test_parser.cc'])
