* guilin-travel
#+TITLE: 桂林山水甲天下

** 2013-07-20
上午11：55在首都国际机场T2坐南方航空CZ3282，下午2：55到桂林的两江机场。刚下飞机就可以从各个方向看到山，属于那种群山环绕的感觉。出发之前预定了在锦江之星的七星店，上面还有一行小字是如果预定成功的话，可以通过发送短信方式告知自己的航班来预约接机的汽车。当天我就把自己的航班信息发送过去了，可是当时我也是半信半疑。因为虽然是在桂林，但是我估计从机场到市区里面还有会有很长的距离的，这个出租车的费用应该也是不便宜的。可以下午2：55刚下飞机的时候果然有一个女的给我了电话，告诉自己就在出口等我。而当我告诉她我还要取行李的时候，她说没有关系可以等不急。当时我就震惊了，尼玛的服务这么到位。即使见到她本人并且上车之后，我脑子里面还一直在想这个问题，会不会到时候她会问我要钱。路上我还特意问她从机场到市区里面打车不太方便吧，她说还是比较远的，打车要100多。

上了车之后，虽然我脑子里面还在想费用这个问题，眼睛却停留在车外面，在观察这个城市。不得不说桂林的绿化做得非常的好，机场到市区整条路上两边都有树而且长得很好，天空的蔚蓝也是许久在京津未见的。差不多开了将近半个小时到一个小时吧，到市区里面了。可是在市区里面绿化也和郊外一样没有马虎，两边马路见的最多的就是桂花树。我没有赶上好的季节，当地人说如果是在秋天桂花树花开的时候，整个桂林市都有一股淡淡的桂花香味。没有赶上好季节的第二个原因是天气太热而湿度太高，这点一出飞机场就感受到了，本来快遗忘蒸桑拿的感觉现在又回忆起来了。但是这个季节来有一个好处，就是人相对比较少还不算是旺季，我去风景区旅游最怕的就是人多破坏了意境。虽然桂林各个时候人都比较多，但是相对来说这个季节这个时分还算是可以的。另外桂林一个比较有意思的现象就是，从地形上来说上下坡比较多（可能没有青岛多），而人们非常喜欢骑电动车和摩托车。后来想清楚大概是为什么了。整个城市上下坡比较多，就决定了自行车这种纯粹靠人力的交通运输方式是不行了，可是汽车相对来说价格比较贵而且机动性不是很好，有些地方还只能是电动车和摩托车才能过，而且电动车和摩托车相对汽车来说便宜不少。在路上我看到了桂林山水甲天下的全对“桂林山水甲天下，玉碧螺清意可参”。

终于到了住的地方，我非常紧张地下车了，但是阿姨很热心地说直接进去就行了，让我一颗悬着的心掉了下来，顿生好感，但是同时思索这个费用怎么来呢？进来酒店办理入住的时候，那里的职员开始给我推荐行程了。因为之前我虽然调查过，但是好多地方还是比较模糊仅仅知道一个地方，各个地方之间的距离以及交通方式都不是很熟悉，也不知道一些经典是否值得去，所以就随意听了一下，然后拿着她给我的报价单上楼看了一下。她给的报价单里面最吸引我的就是，他们所有的行程都是可以包车的，并且不需要添加任何费用，只要从他们那里订购景点游玩，所以我当时在想是否这些交通费用从景点费用里面扣除。但是当时上去拿着报价单和网上的景点零售价格对比才发现，其实是一样的。so why not?!. 到住宿的地方差不多下午5：30了，打算下楼尝一下桂林米线（出门右转就有），顺便就订下来了明天在象鼻山附近做轮船和游靖江王城和独秀峰两个项目和后天去阳朔的项目。轮船费用是100, 靖江王城费用是130，两人一共460.去阳朔的项目首先是去世外桃源，然后到十里画廊上面的几个景点包括鑑山寺，大榕树，月亮山，然后从兴坪做竹筏到杨堤然后返回到兴坪，然后再回阳朔然后回桂林。这个项目是1日游，当天从桂林出发当天回来，费用在350.但是我们打算留在阳朔在看看，所以当晚就不回来了，这样加钱减去了30，两人一共640.

米线确实不错。开始我和我老婆各点了牛腩粉和汤粉二两，价格还算是比较便宜，牛腩粉5.5汤粉5. 粉分为宽粉和圆粉，我觉得圆粉比较好吃，弄好之后可以添加一些排骨汤。一般大家吃粉都是不加汤的，但是我觉得加一些汤会更加好吃。吃完之后还是觉得汤粉是最好吃的，因为它本身没有什么其他的材料还衬托，更加凸显其米粉的味道。所以我建议如果吃桂林米粉的话汤粉会好吃多一点。

吃完了米线我们就乘坐附近的14路公交车到正阳步行街看看。桂林的公交只有1元和2元两种，1元的没有空调，2元的有空调。正阳步行街在刚过解放桥的地方下，走两部就可以看到正阳步行街了。正阳步行街正对的就是靖江王城。沿着步行街很快就走到了末尾，因为整条街也只有666米。走过了步行街就可以看到日月双塔了，再走一下就可以看到两江四湖码头了。可以乘坐船只在绕两江四湖看看，但是我觉得没啥意思，就没有上船只是在附近走走。其实走走还行，晚上虽然还是桑拿天，但是也有习习凉风，走起来还是蛮舒服的。走出日月双塔就有一个电动三轮师傅上前主动询问我们去附近吃小吃，我们正好想在附近吃吃田螺所以就让他带我们去，非常便宜也就是1元，大概走了1公里吧。寻思怎么这么便宜，到了之后才发现，原来大排档和师傅是否回扣可以拿得。去的路上，师傅问我们是否订好了出游路线等。我和他说了我们去阳朔的那段行程，他说我们买贵了实际上我们那段他们只需要275就可以搞下来。当时悔恨不已，后来才知道这个价格和350项目是不同的，低价在漓江上坐的是大船，而高价在漓江上坐的是电动竹筏，而且这个差价在100元。在大排档吃完后在附近买了一些山竹和红毛丹就回宾馆了，这里的山竹不是很贵。

*这里我想提前说一下，整个桂林的旅游业相对来说还是比较正规的。* 一分钱一分货，旅行团给出的价格和散客购买的价格差不多，而且旅行团还附带了一些额外的服务比如包车等。大部分的景点都是明码标价，而且东西是否想要完全是取决于你自己，整体旅游环境还是不错的。但是中途我经过的两个景点不太正规被坑了。一个是阳朔的鉴山寺 ，一个是阳朔的榕树。
   - 桂林鉴山寺和尚大肆骗敛钱财让谁蒙羞？-舆情观察 - : http://forum.china.com.cn/thread-1092447-1-1.html
   - 桂林阳朔大榕树景区“百越壮寨”骗钱坑人！_网易旅游论坛 : http://bbs.travel.163.com/photoalbum/guilin/257641823.html

** 2013-07-21
今天的行程不是很满，早上去

** 2013-07-22
阳朔县内交通其实非常不方便，跟团或者是包车还是比较合理的选择。
