* how-to-apply-domain
#+TITLE: 如何申请域名
   - 首先找到一个域名提供商比如可以找godaddy.（同事xuchaoqian推荐的，不过最近godaddy因为支持SOPA很多注册域名少了很多并且部分站长集体转移域名。GoDaddy支持SOPA 一天痛失2.1万域名 GoDaddy支持SOPA遭抗议 站长集体转移域）注册账户，然后回到godaddy主页就可以申请域名了。
   - 添加到购物车，接着就可以转入结算的流程了。(continue to registration.如果不打算注册其他域名的话，那么就no thanks了)
   - 填写你申请的相关信息。这个还是非常重要的，如果域名出现问题或者是有人想收购你的域名的话，那么可以通过whois服务查找到这个域名的相关信息，就可以直接联系了。付费的大家可以找找godaddy优惠码，可能便宜20%~30%.普通域名差不多就是12$然后加上其他费用差不多人民币80~90左右，便宜20~30%之后的话差不多就是60-70左右/year吧。国内用户允许使用支付宝致富还是比较方便的。搞定之后查看My Account->My Products里面
   - 通常来说很快就会生效的。如果没有生效的话，那么可以发一封信到support@godaddy.com写明自己的Customer(客户号）和订单号(Order).如果生效之后的话那么就可以开始进行配置了。接着进入DNS Manager进行配置（Launch）
   - 将CNAME部分的www删除掉，移到Host下面来，然后配上自己的ip地址即可。
   - 配置成功之后，可以在自己的linux机器上使用whois查看这个域名的信息了。whois dirlt.com

#+BEGIN_VERSE
[dirlt@umeng-ubuntu-pc] > whois dirlt.com

Whois Server Version 2.0

Domain names in the .com and .net domains can now be registered
with many different competing registrars. Go to http://www.internic.net
for detailed information.

   Domain Name: DIRLT.COM
   Registrar: GODADDY.COM, LLC
   Whois Server: whois.godaddy.com
   Referral URL: http://registrar.godaddy.com
   Name Server: NS1.LINODE.COM
   Name Server: NS2.LINODE.COM
   Name Server: NS3.LINODE.COM
   Name Server: NS4.LINODE.COM
   Status: clientDeleteProhibited
   Status: clientRenewProhibited
   Status: clientTransferProhibited
   Status: clientUpdateProhibited
   Updated Date: 20-feb-2012
   Creation Date: 19-dec-2011
   Expiration Date: 19-dec-2012

>>> Last update of whois database: Wed, 29 Aug 2012 07:58:16 UTC <<<

NOTICE: The expiration date displayed in this record is the date the 
registrar's sponsorship of the domain name registration in the registry is 
currently set to expire. This date does not necessarily reflect the expiration 
date of the domain name registrant's agreement with the sponsoring 
registrar.  Users may consult the sponsoring registrar's Whois database to 
view the registrar's reported date of expiration for this registration.

TERMS OF USE: You are not authorized to access or query our Whois 
database through the use of electronic processes that are high-volume and 
automated except as reasonably necessary to register domain names or 
modify existing registrations; the Data in VeriSign Global Registry 
Services' ("VeriSign") Whois database is provided by VeriSign for 
information purposes only, and to assist persons in obtaining information 
about or related to a domain name registration record. VeriSign does not 
guarantee its accuracy. By submitting a Whois query, you agree to abide 
by the following terms of use: You agree that you may use this Data only 
for lawful purposes and that under no circumstances will you use this Data 
to: (1) allow, enable, or otherwise support the transmission of mass 
unsolicited, commercial advertising or solicitations via e-mail, telephone, 
or facsimile; or (2) enable high volume, automated, electronic processes 
that apply to VeriSign (or its computer systems). The compilation, 
repackaging, dissemination or other use of this Data is expressly 
prohibited without the prior written consent of VeriSign. You agree not to 
use electronic processes that are automated and high-volume to access or 
query the Whois database except as reasonably necessary to register 
domain names or modify existing registrations. VeriSign reserves the right 
to restrict your access to the Whois database in its sole discretion to ensure 
operational stability.  VeriSign may restrict or terminate your access to the 
Whois database for failure to abide by these terms of use. VeriSign 
reserves the right to modify these terms at any time. 

The Registry database contains ONLY .COM, .NET, .EDU domains and
Registrars.
The data contained in GoDaddy.com, LLC's WhoIs database,
while believed by the company to be reliable, is provided "as is"
with no guarantee or warranties regarding its accuracy.  This
information is provided for the sole purpose of assisting you
in obtaining information about domain name registration records.
Any use of this data for any other purpose is expressly forbidden without the prior written
permission of GoDaddy.com, LLC.  By submitting an inquiry,
you agree to these terms of usage and limitations of warranty.  In particular,
you agree not to use this data to allow, enable, or otherwise make possible,
dissemination or collection of this data, in part or in its entirety, for any
purpose, such as the transmission of unsolicited advertising and
and solicitations of any kind, including spam.  You further agree
not to use this data to enable high volume, automated or robotic electronic
processes designed to collect or compile this data for any purpose,
including mining this data for your own personal or commercial purposes. 

Please note: the registrant of the domain name is specified
in the "registrant" field.  In most cases, GoDaddy.com, LLC 
is not the registrant of domain names listed in this database.


Registrant:
   dirty salt
   Shangdi 10th Street Haidian District
   Beijing, Beijing 100085
   China

   Registered through: GoDaddy.com, LLC (http://www.godaddy.com)
   Domain Name: DIRLT.COM
      Created on: 19-Dec-11
      Expires on: 19-Dec-12
      Last Updated on: 20-Feb-12

   Administrative Contact:
      salt, dirty  dirtysalt1987@gmail.com
      Shangdi 10th Street Haidian District
      Beijing, Beijing 100085
      China
      8615210717839

   Technical Contact:
      salt, dirty  dirtysalt1987@gmail.com
      Shangdi 10th Street Haidian District
      Beijing, Beijing 100085
      China
      8615210717839

   Domain servers in listed order:
      NS1.LINODE.COM
      NS2.LINODE.COM
      NS3.LINODE.COM
      NS4.LINODE.COM
#+END_VERSE
