#!/bin/bash
# go doc server
function start() {
    echo "godoc -http=:6060"
    godoc -http=:6060
}

function stop() {
    for pid in `ps aux | grep "godoc -http=:6060" | grep -v "grep" | awk '{print $2;}'`
    do
        echo "sudo kill -9 $pid of 'godoc -http=:6060'"
        sudo kill -9 $pid
    done    
}

stop
start



