#!/usr/bin/env python
#coding:utf-8
#Copyright (C) dirlt

import string
import os
import sys

def org2twiki(lns):
    nlns=[]    
    kTextMode=0 # interpret text.
    kRawMode=1 # copy text.
    status=kTextMode    
    for ln in lns:
        #kRawMode.
        if(status==kRawMode):
            # example mode.
            if(string.strip(ln)=='#+END_EXAMPLE'):
                nlns.append('</pre>')
                status=kTextMode
            # source mode.
            elif(string.strip(ln)=='#+END_SRC'):
                nlns.append('%ENDGESHI%')
                status=kTextMode
            # verse mode.
            elif(string.strip(ln)=='#+END_VERSE'):
                nlns.append('</blockquote>')
                status=kTextMode
            else: # else.
                nlns.append(ln)
            continue
    
        
        #kTextMode.
        if(ln.startswith('* ') or
           ln.startswith('**')):
            # captain.
            # handle *NOTE(dirlt)* this format.
            (captag,content)=string.split(ln,maxsplit=1)            
            depth=len(captag)+1
            nlns.append('---%s %s'%('+'*depth,content))
        elif(string.strip(ln).startswith('#+')):
            ln=string.strip(ln)
            if(ln=='#+BEGIN_EXAMPLE'):
                # example mode.
                nlns.append('<pre>')
                status=kRawMode
            elif(ln.startswith('#+BEGIN_SRC')):
                # source mode.
                mode=string.split(ln,maxsplit=1)[1]
                nlns.append('%%GESHI{"%s"}%%'%(string.lower(mode)))
                status=kRawMode
            elif(ln=='#+BEGIN_VERSE'):
                # verse mode.
                nlns.append('<blockquote>')
                status=kRawMode                
            elif(ln.startswith("#+AUTHOR:") or
                 ln.startswith("#+OPTIONS:") or
                 ln.startswith('#+TITLE:') or
                 ln.startswith('#+ -*- org -*-')):
                # some meta info.
                pass
            else:
                nlns.append(ln)
        #table header.
        elif(ln.startswith('|--')):
            pass
        else:
            nlns.append(ln)
    return nlns

def main(fname):
    (root,_)=os.path.splitext(fname)
    base=os.path.basename(root)
    nfname='%s.twiki.txt'%(root)
    lns=map(lambda x:string.rstrip(x),open(fname).readlines())
    nlns=[]
    # with table of content.
    nlns.append('---# %s'%(base))
    nlns.append('%TOC%')
    nlns.extend(org2twiki(lns))
    open(nfname,'w').writelines(map(lambda x:'%s\n'%x,nlns))
    return 

if __name__=='__main__':
    if(len(sys.argv)!=2):
        print "convert emacs org to twiki"
        print "usage:%s FILENAME"%(sys.argv[0])
        sys.exit(-1)
    main(sys.argv[1])
