#!/usr/bin/env bash
#Copyright (C) dirlt

echo "patching fast-hbase-rest ..."
rsync -avrz $HOME/github/fast-hbase-rest/src/main/java/ $HOME/github/sperm/code/java/fast-hbase-rest/src/main/java/
rsync -avrz $HOME/github/fast-hbase-rest/src/main/proto/ $HOME/github/sperm/code/java/fast-hbase-rest/src/main/proto/

