#!/usr/bin/env python
#coding:utf-8
#Copyright (C) dirlt

POM_TEMPLATE="""<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>%(groupId)s</groupId>
  <artifactId>%(artifactId)s</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>%(project)s</name>
  <url>http://dirlt.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <distributionManagement>    
    <repository>
      <id>releases</id>
      <name>Release Repository</name>
      <url>http://nexus:8088/nexus/content/repositories/releases/</url>
    </repository>
    <snapshotRepository>
      <id>snapshots</id>
      <name>Snapshot Repository</name>
      <url>http://nexus:8088/nexus/content/repositories/snapshots/</url>
    </snapshotRepository>
  </distributionManagement>
  
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.8.2</version>
      <scope>test</scope>
    </dependency>

    <!-- <dependency> -->
    <!--   <groupId>com.google.protobuf</groupId> -->
    <!--   <artifactId>protobuf-java</artifactId> -->
    <!--   <version>2.3.0</version> -->
    <!-- </dependency> -->
  </dependencies>
  
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>2.5.1</version>
        <configuration>
          <source>1.6</source>
          <target>1.6</target>
        </configuration>
      </plugin>    

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <configuration>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
        </configuration>
        <executions>
          <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <!-- <plugin> -->
      <!--   <groupId>org.codehaus.mojo</groupId> -->
      <!--   <artifactId>build-helper-maven-plugin</artifactId> -->
      <!--   <version>1.8</version> -->
      <!--   <executions> -->
      <!--     <execution> -->
      <!--       <phase>generate-sources</phase> -->
      <!--       <goals><goal>add-source</goal></goals> -->
      <!--       <configuration> -->
      <!--         <sources> -->
      <!--           <source>src/main/gen-java</source> -->
      <!--           <source>src/main/resources</source> -->
      <!--         </sources> -->
      <!--       </configuration> -->
      <!--     </execution> -->
      <!--   </executions> -->
      <!-- </plugin> -->

      <!-- <plugin> -->
      <!--   <artifactId>maven-antrun-plugin</artifactId> -->
      <!--   <executions> -->
      <!--     <execution> -->
      <!--       <id>generate-sources</id> -->
      <!--       <phase>generate-sources</phase> -->
      <!--       <configuration> -->
      <!--         <tasks> -->
      <!--           <mkdir dir="src/main/gen-java"/> -->
      <!--           <exec executable="protoc"> -->
      <!--             <arg value="src/main/proto/message.proto"/> -->
      <!--           </exec> -->
      <!--         </tasks> -->
      <!--         <sourceRoot>src/main/gen-java</sourceRoot> -->
      <!--       </configuration> -->
      <!--       <goals> -->
      <!--         <goal>run</goal> -->
      <!--       </goals> -->
      <!--     </execution> -->
      <!--   </executions> -->
      <!-- </plugin> -->
    </plugins>
  </build>

</project>
"""

MAKEFILE_TEMPLATE="""#coding:utf-8
#Copyright (C) dirlt

# mostly this works.
copy-unpack-dependency:
	mvn dependency:unpack-dependencies

# if the above command failed. please use this one.
copy-unpack-dependency2:
	mvn dependency:copy-dependencies ; cd ./target/dependency ; for x in *.jar ; do echo "jar xf $$x ..." ; jar xf $$x ; done

"""

import os
def generate(project,groupId,artifactId):
    cps=groupId.split('.')
    cps.append(artifactId)
    os.system('mkdir -p %s'%(project))
    open('%s/pom.xml'%(project),'w').write(POM_TEMPLATE%(locals()))
    open('%s/Makefile'%(project),'w').write(MAKEFILE_TEMPLATE%(locals()))
    os.system('mkdir -p %s/src/main/java/%s/'%(project,'/'.join(cps)))
    os.system('mkdir -p %s/src/test/java/%s/'%(project,'/'.join(cps)))
    os.system('mkdir -p %s/src/main/resources/'%(project))
    os.system('mkdir -p %s/src/test/resources/'%(project))

import sys
if __name__=='__main__':
    if(len(sys.argv)!=4):
        print 'create a new project in maven'
        print 'usage:%s project-name groupId artifactId'%(sys.argv[0])
    else:
        generate(sys.argv[1],sys.argv[2],sys.argv[3])
