#!/usr/bin/env python
#coding:utf-8
#Copyright (C) dirlt

# install ubuntu packages.
import os
import string
import sys
curdir=os.path.dirname(os.path.realpath(__file__))
ubuntu=os.path.join(curdir,'essay','ubuntu.org')
xs=map(lambda x:string.strip(x),open(ubuntu).readlines())
pkgs=[]
prefix='- sudo apt-get install '
for x in xs:    
    if(x.startswith(prefix)):
        x=x[len(prefix):]
        x=x.split('#')[0]
        pkgs.append(x)

print pkgs
cmd='sudo apt-get install %s'%(' '.join(pkgs))
print cmd
os.system(cmd)


