#!/usr/bin/env python
#coding:gbk
#Copyright (C) dirlt

import os
# --------------------common--------------------
env=Environment(CPPPATH=['.'],
                CXXFLAGS='-W -Wall -g -Werror -Wno-unused-parameter -O2 -UDEBUG -fPIC')
env.StaticLibrary('common/common',Glob('common/*.cc'))

# --------------------sasuke--------------------
env=Environment(CPPPATH=['.'],
                CXXFLAGS='-W -Wall -g -Werror -O2 -DDEBUG -fPIC')
env.StaticLibrary('sasuke/sasuke',Glob('sasuke/rpc.cc'))

# --------------------itachi--------------------
env=Environment(CPPPATH=['.'],
                CXXFLAGS='-W -Wall -g -Werror -O2 -UDEBUG -fPIC')
env.StaticLibrary('itachi/itachi',['itachi/itachi.cc','itachi/handler.cc',
                                   'itachi/asocket.cc'])

# --------------------astyle--------------------
env=Environment(CPPPATH=['.'],
                CXXFLAGS='-W -Wall -g -Werror -O2 -DDEBUG -fPIC -DASTYLE_LIB')
env.StaticLibrary('astyle/astyle',Glob('astyle/*.cc')+Glob('astyle/*.cpp'))

# --------------------nasty--------------------
env=Environment(CPPPATH=['.'],
                CXXFLAGS='-W -Wall -g -Werror -Wno-unused-parameter -Wno-unused-function -O2 -DDEBUG -fPIC')
env.StaticLibrary('nasty/nasty',Glob('nasty/*.cc'))

SConscript(['common/test/SConstruct',
            'sasuke/test/SConstruct',
            'itachi/test/SConstruct',
            'bench/SConstruct',
            'astyle/test/SConstruct',
            'nasty/test/SConstruct'])

