#!/bin/bash
#/usr/bin/python /usr/lib/jvm/java-6-sun/jre/bin/strace-java.py $@
#LD_PRELOAD="/usr/lib64/libtcmalloc.so.4" /usr/lib/jvm/java-6-sun/jre/bin/.java $@
/usr/lib/jvm/java-6-sun/jre/bin/.java $@
